FROM node:22-alpine

WORKDIR /app

# зависимости
COPY package*.json ./
RUN npm install

# исходники
COPY . .

EXPOSE 5173

# важно: слушать на 0.0.0.0, иначе порт не пробросится
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
